In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("Dataset_1.csv")
df

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,250.5,2023-01-15,Debit Card,NaN,5,True
1,ORD1001,NaN,18.0,1200,2023/03/10,Debit Card,NaN,5,yes
2,ORD1002,CUST2,35.0,NaN,NaN,NaN,Mumbai,7,yes
3,ORD1003,user_3,35.0,1200,2023-01-15,Cash,NaN,three,False
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,CARD,NaN,three,yes
...,...,...,...,...,...,...,...,...,...
995,NaN,user_995,-3.0,3500.75,15/02/2023,upi,Mumbai,1,True
996,NaN,CUST996,18.0,NaN,2023-01-15,Credit Card,Hyderabad,2,yes
997,NaN,user_997,50.0,NaN,2023/03/10,Cash,Delhi,1,NaN
998,ORD1998,NaN,65.0,1200,2023-01-15,NaN,Mumbai,2,False
999,NaN,user_999,120.0,NaN,15/02/2023,Debit Card,NaN,-1,True

In [6]:
#Identify all rows where order_amount is non-numeric but is_delivered is marked as delivered
amount_numeric = pd.to_numeric(df['order_amount'], errors='coerce')
result = df[
    amount_numeric.isna() &
    (df['is_delivered'] == 'delivered')
]

print(result)

Empty DataFrame
Columns: [order_id, customer_id, customer_age, order_amount, order_date, payment_mode, city, delivery_days, is_delivered]
Index: []

In [7]:
df

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,250.5,2023-01-15,Debit Card,NaN,5,True
1,ORD1001,NaN,18.0,1200,2023/03/10,Debit Card,NaN,5,yes
2,ORD1002,CUST2,35.0,NaN,NaN,NaN,Mumbai,7,yes
3,ORD1003,user_3,35.0,1200,2023-01-15,Cash,NaN,three,False
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,CARD,NaN,three,yes
...,...,...,...,...,...,...,...,...,...
995,NaN,user_995,-3.0,3500.75,15/02/2023,upi,Mumbai,1,True
996,NaN,CUST996,18.0,NaN,2023-01-15,Credit Card,Hyderabad,2,yes
997,NaN,user_997,50.0,NaN,2023/03/10,Cash,Delhi,1,NaN
998,ORD1998,NaN,65.0,1200,2023-01-15,NaN,Mumbai,2,False
999,NaN,user_999,120.0,NaN,15/02/2023,Debit Card,NaN,-1,True

In [8]:
df['is_delivered']

0       True
1        yes
2        yes
3      False
4        yes
       ...
995     True
996      yes
997      NaN
998    False
999     True
Name: is_delivered, Length: 1000, dtype: object

In [9]:
## convert it to lowercase is_delivered column and repace yes as true and no as false
df['is_delivered']=df['is_delivered'].str.lower().replace('yes','true')

In [10]:
df

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,250.5,2023-01-15,Debit Card,NaN,5,true
1,ORD1001,NaN,18.0,1200,2023/03/10,Debit Card,NaN,5,true
2,ORD1002,CUST2,35.0,NaN,NaN,NaN,Mumbai,7,true
3,ORD1003,user_3,35.0,1200,2023-01-15,Cash,NaN,three,false
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,CARD,NaN,three,true
...,...,...,...,...,...,...,...,...,...
995,NaN,user_995,-3.0,3500.75,15/02/2023,upi,Mumbai,1,true
996,NaN,CUST996,18.0,NaN,2023-01-15,Credit Card,Hyderabad,2,true
997,NaN,user_997,50.0,NaN,2023/03/10,Cash,Delhi,1,NaN
998,ORD1998,NaN,65.0,1200,2023-01-15,NaN,Mumbai,2,false
999,NaN,user_999,120.0,NaN,15/02/2023,Debit Card,NaN,-1,true

In [11]:
df['is_delivered']=df['is_delivered'].str.lower().replace('no','false')

In [12]:
df

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
0,ORD1000,NaN,NaN,250.5,2023-01-15,Debit Card,NaN,5,true
1,ORD1001,NaN,18.0,1200,2023/03/10,Debit Card,NaN,5,true
2,ORD1002,CUST2,35.0,NaN,NaN,NaN,Mumbai,7,true
3,ORD1003,user_3,35.0,1200,2023-01-15,Cash,NaN,three,false
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,CARD,NaN,three,true
...,...,...,...,...,...,...,...,...,...
995,NaN,user_995,-3.0,3500.75,15/02/2023,upi,Mumbai,1,true
996,NaN,CUST996,18.0,NaN,2023-01-15,Credit Card,Hyderabad,2,true
997,NaN,user_997,50.0,NaN,2023/03/10,Cash,Delhi,1,NaN
998,ORD1998,NaN,65.0,1200,2023-01-15,NaN,Mumbai,2,false
999,NaN,user_999,120.0,NaN,15/02/2023,Debit Card,NaN,-1,true

In [13]:
df['order_amount'].isna()

0      False
1      False
2       True
3      False
4      False
       ...
995    False
996     True
997     True
998    False
999     True
Name: order_amount, Length: 1000, dtype: bool

In [14]:
# convert order_date to datetime and find orders where delivery_days is negative after valid date conversion
df['order_date'].unique()

array(['2023-01-15', '2023/03/10', nan, 'invalid', '15/02/2023'],
      dtype=object)

In [15]:
df['order_date']=pd.to_datetime(df['order_date'],errors='coerce',dayfirst=True)

C:\Users\chand\AppData\Local\Temp\ipykernel_23424\35690639.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['order_date']=pd.to_datetime(df['order_date'],errors='coerce',dayfirst=True)

In [16]:
df['order_date']

0     2023-01-15
1            NaT
2            NaT
3     2023-01-15
4     2023-01-15
         ...
995          NaT
996   2023-01-15
997          NaT
998   2023-01-15
999          NaT
Name: order_date, Length: 1000, dtype: datetime64[ns]

In [17]:
df['delivery_days']=pd.to_numeric(df['delivery_days'],errors='coerce')

In [18]:
df['delivery_days']

0      5.0
1      5.0
2      7.0
3      NaN
4      NaN
      ...
995    1.0
996    2.0
997    1.0
998    2.0
999   -1.0
Name: delivery_days, Length: 1000, dtype: float64

In [19]:
s=df[df['order_date'].notna() & df['delivery_days'].notna() & (df['delivery_days']<0)]
s

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
99,NaN,NaN,50.0,250.5,2023-01-15,Debit Card,Hyderabad,-1.0,NaN
115,ORD1115,NaN,-3.0,250.5,2023-01-15,Cash,mumbai,-1.0,false
143,NaN,user_143,25.0,3500.75,2023-01-15,Debit Card,Hyderabad,-1.0,NaN
155,NaN,CUST155,NaN,499.99,2023-01-15,upi,Delhi,-1.0,true
170,NaN,NaN,NaN,1200,2023-01-15,Cash,DELHI,-1.0,true
238,ORD1238,user_238,NaN,NaN,2023-01-15,CARD,DELHI,-1.0,false
270,NaN,NaN,35.0,₹999,2023-01-15,CARD,Delhi,-1.0,false
272,NaN,user_272,65.0,NaN,2023-01-15,UPI,NaN,-1.0,NaN
303,ORD1303,user_303,35.0,250.5,2023-01-15,Cash,Hyderabad,-1.0,false
334,NaN,user_334,50.0,499.99,2023-01-15,upi,Delhi,-1.0,false
407,NaN,NaN,65.0,1200,2023-01-15,CARD,DELHI,-1.0,true
429,NaN,user_429,35.0,₹999,2023-01-15,CARD,NaN,-1.0,NaN
493,NaN,NaN,-3.0,1200,2023-01-15,CARD,Hyderabad,-1.0,false
561,NaN,user_561,25.0,3500.75,2023-01-15,upi,DELHI,-1.0,true
628,NaN,NaN,50.0,₹999,2023-01-15,upi,Delhi,-1.0,false
639,NaN,CUST639,-3.0,499.99,2023-01-15,Cash,DELHI,-1.0,false
674,NaN,NaN,18.0,₹999,2023-01-15,upi,mumbai,-1.0,true
720,ORD1720,NaN,35.0,1200,2023-01-15,upi,NaN,-1.0,false
726,NaN,NaN,NaN,499.99,2023-01-15,upi,Hyderabad,-1.0,false
741,ORD1741,CUST741,50.0,250.5,2023-01-15,UPI,Mumbai,-1.0,true
751,ORD1751,NaN,35.0,NaN,2023-01-15,Cash,Delhi,-1.0,true
763,NaN,NaN,NaN,250.5,2023-01-15,Debit Card,DELHI,-1.0,NaN
780,ORD1780,NaN,25.0,NaN,2023-01-15,upi,Hyderabad,-1.0,true
838,NaN,user_838,NaN,3500.75,2023-01-15,NaN,Mumbai,-1.0,false
880,ORD1880,user_880,35.0,1200,2023-01-15,Cash,Mumbai,-1.0,true
934,NaN,NaN,-3.0,NaN,2023-01-15,UPI,mumbai,-1.0,false
937,ORD1937,CUST937,-3.0,NaN,2023-01-15,Debit Card,mumbai,-1.0,true
945,ORD1945,NaN,NaN,250.5,2023-01-15,NaN,mumbai,-1.0,false

In [20]:

#standardize payment_mode and calculate the  percentage share of each mode per city
s=df.groupby(["city","payment_mode"]).size()
s

city       payment_mode
Bangalore  CARD            25
           Cash            22
           Credit Card     15
           Debit Card      24
           UPI             27
           upi             15
DELHI      CARD            19
           Cash            23
           Credit Card     21
           Debit Card      25
           UPI             20
           upi             19
Delhi      CARD            29
           Cash            23
           Credit Card     20
           Debit Card      24
           UPI             26
           upi             24
Hyderabad  CARD            23
           Cash            20
           Credit Card     18
           Debit Card      20
           UPI             12
           upi             24
Mumbai     CARD            13
           Cash            25
           Credit Card     15
           Debit Card      24
           UPI             26
           upi             18
mumbai     CARD            18
           Cash            19
           Credit Card     17
           Debit Card      12
           UPI             21
           upi             16
dtype: int64

In [21]:




df['payment_mode']=df['payment_mode'].str.strip().str.lower()

In [22]:
df['payment_mode']

0       debit card
1       debit card
2              NaN
3             cash
4             card
          ...
995            upi
996    credit card
997           cash
998            NaN
999     debit card
Name: payment_mode, Length: 1000, dtype: object

In [23]:
df['city']=df['city'].str.strip().str.lower()

In [24]:
df['city']

0            NaN
1            NaN
2         mumbai
3            NaN
4            NaN
         ...
995       mumbai
996    hyderabad
997        delhi
998       mumbai
999          NaN
Name: city, Length: 1000, dtype: object

In [25]:
percentage=s/s.groupby(level=0).sum()*100
percentage

city       payment_mode
Bangalore  CARD            19.531250
           Cash            17.187500
           Credit Card     11.718750
           Debit Card      18.750000
           UPI             21.093750
           upi             11.718750
DELHI      CARD            14.960630
           Cash            18.110236
           Credit Card     16.535433
           Debit Card      19.685039
           UPI             15.748031
           upi             14.960630
Delhi      CARD            19.863014
           Cash            15.753425
           Credit Card     13.698630
           Debit Card      16.438356
           UPI             17.808219
           upi             16.438356
Hyderabad  CARD            19.658120
           Cash            17.094017
           Credit Card     15.384615
           Debit Card      17.094017
           UPI             10.256410
           upi             20.512821
Mumbai     CARD            10.743802
           Cash            20.661157
           Credit Card     12.396694
           Debit Card      19.834711
           UPI             21.487603
           upi             14.876033
mumbai     CARD            17.475728
           Cash            18.446602
           Credit Card     16.504854
           Debit Card      11.650485
           UPI             20.388350
           upi             15.533981
dtype: float64

In [26]:
percentage_df=percentage.reset_index(name='percentage')
percentage_df

         city payment_mode  percentage
0   Bangalore         CARD   19.531250
1   Bangalore         Cash   17.187500
2   Bangalore  Credit Card   11.718750
3   Bangalore   Debit Card   18.750000
4   Bangalore          UPI   21.093750
5   Bangalore          upi   11.718750
6       DELHI         CARD   14.960630
7       DELHI         Cash   18.110236
8       DELHI  Credit Card   16.535433
9       DELHI   Debit Card   19.685039
10      DELHI          UPI   15.748031
11      DELHI          upi   14.960630
12      Delhi         CARD   19.863014
13      Delhi         Cash   15.753425
14      Delhi  Credit Card   13.698630
15      Delhi   Debit Card   16.438356
16      Delhi          UPI   17.808219
17      Delhi          upi   16.438356
18  Hyderabad         CARD   19.658120
19  Hyderabad         Cash   17.094017
20  Hyderabad  Credit Card   15.384615
21  Hyderabad   Debit Card   17.094017
22  Hyderabad          UPI   10.256410
23  Hyderabad          upi   20.512821
24     Mumbai         CARD   10.743802
25     Mumbai         Cash   20.661157
26     Mumbai  Credit Card   12.396694
27     Mumbai   Debit Card   19.834711
28     Mumbai          UPI   21.487603
29     Mumbai          upi   14.876033
30     mumbai         CARD   17.475728
31     mumbai         Cash   18.446602
32     mumbai  Credit Card   16.504854
33     mumbai   Debit Card   11.650485
34     mumbai          UPI   20.388350
35     mumbai          upi   15.533981

In [27]:
## Detect customers whose customer_age is invalid but have order amounts above the dataset median
df['customer_age']=pd.to_numeric(df['customer_age'],errors='coerce')
df['customer_age']

0        NaN
1       18.0
2       35.0
3       35.0
4       -3.0
       ...
995     -3.0
996     18.0
997     50.0
998     65.0
999    120.0
Name: customer_age, Length: 1000, dtype: float64

In [28]:
df['order_amount']=pd.to_numeric(df['order_amount'],errors='coerce')
df['order_amount']

0       250.50
1      1200.00
2          NaN
3      1200.00
4      3500.75
        ...
995    3500.75
996        NaN
997        NaN
998    1200.00
999        NaN
Name: order_amount, Length: 1000, dtype: float64

In [29]:
df.median

<bound method DataFrame.median of     order_id customer_id  customer_age  order_amount order_date payment_mode  \
0    ORD1000         NaN           NaN        250.50 2023-01-15   debit card
1    ORD1001         NaN          18.0       1200.00        NaT   debit card
2    ORD1002       CUST2          35.0           NaN        NaT          NaN
3    ORD1003      user_3          35.0       1200.00 2023-01-15         cash
4    ORD1004      user_4          -3.0       3500.75 2023-01-15         card
..       ...         ...           ...           ...        ...          ...
995      NaN    user_995          -3.0       3500.75        NaT          upi
996      NaN     CUST996          18.0           NaN 2023-01-15  credit card
997      NaN    user_997          50.0           NaN        NaT         cash
998  ORD1998         NaN          65.0       1200.00 2023-01-15          NaN
999      NaN    user_999         120.0           NaN        NaT   debit card

          city  delivery_days is_delivered
0          NaN            5.0         true
1          NaN            5.0         true
2       mumbai            7.0         true
3          NaN            NaN        false
4          NaN            NaN         true
..         ...            ...          ...
995     mumbai            1.0         true
996  hyderabad            2.0         true
997      delhi            1.0          NaN
998     mumbai            2.0        false
999        NaN           -1.0         true

[1000 rows x 9 columns]>

In [30]:
m=df['order_amount'].median()
m

499.99

In [31]:
d=df[df['customer_age'].isna()  & (df['order_amount']>m)]
d

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered
5,NaN,NaN,NaN,1200.00,2023-01-15,card,mumbai,1.0,false
37,NaN,NaN,NaN,3500.75,NaT,card,mumbai,7.0,NaN
44,ORD1044,NaN,NaN,3500.75,NaT,upi,mumbai,NaN,true
75,NaN,CUST75,NaN,1200.00,NaT,upi,delhi,1.0,false
76,NaN,NaN,NaN,3500.75,NaT,NaN,hyderabad,-1.0,true
...,...,...,...,...,...,...,...,...,...
895,ORD1895,user_895,NaN,1200.00,NaT,debit card,bangalore,NaN,true
902,NaN,user_902,NaN,1200.00,NaT,upi,hyderabad,NaN,true
924,NaN,NaN,NaN,3500.75,2023-01-15,card,bangalore,NaN,true
930,ORD1930,NaN,NaN,1200.00,NaT,NaN,delhi,1.0,true
989,ORD1989,NaN,NaN,1200.00,2023-01-15,upi,mumbai,NaN,false

In [34]:
## find duplicate customer_ids where the same customer placed orders in multiple cities
df['customer_id'].nunique

<bound method IndexOpsMixin.nunique of 0           NaN
1           NaN
2         CUST2
3        user_3
4        user_4
         ...
995    user_995
996     CUST996
997    user_997
998         NaN
999    user_999
Name: customer_id, Length: 1000, dtype: object>

In [41]:

duplicate_customers=df.groupby('customer_id')['city'].nunique()
duplicate_customers

customer_id
CUST108     1
CUST11      1
CUST111     1
CUST117     1
CUST119     1
           ..
user_97     1
user_977    1
user_995    1
user_997    1
user_999    0
Name: city, Length: 489, dtype: int64

In [56]:
## create a flag for orders where delivery_days is misssing but is_delivered is True
df['delivery_days_missing_flag']=df.apply(lambda row: 1 if pd.isna(row['delivery_days']) and row['is_delivered'] == 'true' else 0,axis=1)

In [54]:
df['delivery_days_missing_flag']

0      0
1      0
2      0
3      0
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: delivery_days_missing_flag, Length: 1000, dtype: int64

In [50]:
df

,order_id,customer_id,customer_age,order_amount,order_date,payment_mode,city,delivery_days,is_delivered,delivery_days_missing_flag
0,ORD1000,NaN,NaN,250.50,2023-01-15,debit card,NaN,5.0,true,0
1,ORD1001,NaN,18.0,1200.00,NaT,debit card,NaN,5.0,true,0
2,ORD1002,CUST2,35.0,NaN,NaT,NaN,mumbai,7.0,true,0
3,ORD1003,user_3,35.0,1200.00,2023-01-15,cash,NaN,NaN,false,0
4,ORD1004,user_4,-3.0,3500.75,2023-01-15,card,NaN,NaN,true,1
...,...,...,...,...,...,...,...,...,...,...
995,NaN,user_995,-3.0,3500.75,NaT,upi,mumbai,1.0,true,0
996,NaN,CUST996,18.0,NaN,2023-01-15,credit card,hyderabad,2.0,true,0
997,NaN,user_997,50.0,NaN,NaT,cash,delhi,1.0,NaN,0
998,ORD1998,NaN,65.0,1200.00,2023-01-15,NaN,mumbai,2.0,false,0
999,NaN,user_999,120.0,NaN,NaT,debit card,NaN,-1.0,true,0

In [57]:
# after cleaning,compute the average  order value per payment mode,excluding invalid amount
df['order_amount'].isnull

<bound method Series.isnull of 0       250.50
1      1200.00
2          NaN
3      1200.00
4      3500.75
        ...
995    3500.75
996        NaN
997        NaN
998    1200.00
999        NaN
Name: order_amount, Length: 1000, dtype: float64>

In [60]:
avg_order=df.groupby('payment_mode')['order_amount'].mean()
data=avg_order.reset_index(name="avg")

In [61]:
data

  payment_mode          avg
0         card  1553.016237
1         cash  1414.393708
2  credit card  1243.262656
3   debit card  1432.739318
4          upi  1349.349091

In [64]:
# Identify cities where more than 30% of orders have missing order_date
missing=df.groupby('city')['order_date'].apply(lambda x: x.isna().mean()*100)
above30=missing[missing>30]
above30

city
bangalore    80.794702
delhi        80.463576
hyderabad    84.397163
mumbai       74.242424
Name: order_date, dtype: float64